export const LOGIN_SUCCESS_REQUEST = "LOGIN_SUCCESS_REQUEST";
export const LOGIN_SUCCESS_SUCCESS = "LOGIN_SUCCESS_SUCCESS";
export const LOGIN_SUCCESS_FAILURE = "LOGIN_SUCCESS_FAILURE";

export const REGISTER_SUCCESS_REQUEST = "REGISTER_SUCCESS_REQUEST";
export const REGISTER_SUCCESS_SUCCESS = "REGISTER_SUCCESS_SUCCESS";
export const REGISTER_SUCCESS_FAILURE = "REGISTER_SUCCESS_FAILURE";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const UPDATED_PROFILE_REQUEST = "UPDATED_PROFILE_REQUEST";
export const UPDATED_PROFILE_SUCCESS = "UPDATED_PROFILE_SUCCESS";
export const UPDATED_PROFILE_FAILURE = "UPDATED_PROFILE_FAILURE";
export const UPDATED_PROFILE_RESET = "UPDATED_PROFILE_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
